name: Docker Image CI

on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Build the Docker image
      run: docker build ./DockerImages/cms/ --file dockerfile --tag my-image-name:$(date +%s)
      
